server:
  port: 8761 
eureka:
  instance:
  #spring cloud eureka默认是使用hostname进行注册的，如果要使用ip注册，可以这样设置
    #hostname: peer1
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server
